# Generated by Django 5.0.7 on 2024-07-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madhuramkitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='recommened_dish',
            field=models.BooleanField(default=False),
        ),
    ]
